#!/usr/bin/env bash

function create_node_env_variables () {
    echo "** LOADING ENV VARIABLES **"
    echo "
      PORT = $PORT
      DATABASE_URL_TEST = $DATABASE_URL_TEST
      NODE_ENV = 'test'
      JWT_SECRET = $JWT_SECRET
      SENDGRID_API_KEY = $SENDGRID_API_KEY
      GOOGLE_CLIENT_ID = $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET = $GOOGLE_CLIENT_SECRET
      FACEBOOK_CLIENT_ID = $FACEBOOK_CLIENT_ID
      FACEBOOK_CLIENT_SECRET = $FACEBOOK_CLIENT_SECRET
      LINKEDIN_CLIENT_ID = $LINKEDIN_CLIENT_ID
      LINKEDIN_CLIENT_SECRET = $LINKEDIN_CLIENT_SECRET
      TWITTER_CLIENT_ID = '$TWITTER_CLIENT_ID
      TWITTER_CLIENT_SECRET = $TWITTER_CLIENT_SECRET
      SESSION_SECRET = $SESSION_SECRET
      PUSHER_APP_ID = $PUSHER_APP_ID
      PUSHER_KEY = $PUSHER_KEY
      PUSHER_SECRET = $PUSHER_SECRET
      PUSHER_CLUSTER = $PUSHER_CLUSTER
      SUPER_ADMIN_ROLE_ID = $SUPER_ADMIN_ROLE_ID
      SUPER_ADMIN_FULLNAME = $SUPER_ADMIN_FULLNAME
      SUPER_ADMIN_USERNAME = $SUPER_ADMIN_USERNAME
      SUPER_ADMIN_EMAIL = $SUPER_ADMIN_EMAIL
      SUPER_ADMIN_PASSWORD = $SUPER_ADMIN_PASSWORD
      SUPER_ADMIN_AUTHTYPEID = $SUPER_ADMIN_AUTHTYPEID" >> .env
    echo "** DONE **"
}

function main() {
    create_node_env_variables
}

main

